language: python
python:
  - "3.6"  
  - "3.7"
  - "3.8"
install:
  - pip install pytest mypy pylint pytest-cov codecov
  - pip install -e '.[testing]'
script:
  - mypy mosaic
  - pylint -E mosaic
  - pytest --cov=./
after_success:
  - codecov
