language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install '.[testing]'
# command to run tests
script:
  - mypy mosaic
  - pylint -E mosaic
  - pytest
